package com.moddakir.moddakir.network.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class User(
    var currentlyLogged: Boolean = false,
    val id: String,
    var accessToken: String,
    val teacherPreferenceLabel: String,
    val totalPreferanceScore: Double,
    val fullName: String,
    val email: String?,
    var lastTime: Long = 0,
    var isChildDependent: Boolean = false,
    var orderForChild: Int = 0,
    val phone: String,
    val gender: String,
    val username: String,
    val pass: String,
    val country: String,
    val city: String,
    val brief: String,
    val certificate: String,
    val address: String,
    val status: String,
    val avatarUrl: String,
    val logged_in: Boolean = false,
    val isFav: Boolean = false,
    val isSubscribed: Boolean = false,
    val ejaza: String,
    val languages: String,
    val yearsOfExperience: String,
    val totalStudents: String,
    val availableTimePerWeek: String,
    val sinchId: String,
    val technicalExperience: String,
    val parent: String,
    val requested_date: String,
    val search_type: String,
    val rate: Float = 0f,
    val totalRate: Float = 0f,
    var isDependentManager: Boolean = false,
    var enableVoiceRecording: Boolean = false,
    var enableVideoRecording: Boolean = false,
    val assignmentValue: Float = 0f,
    val studentComments: List<com.moddakir.moddakir.network.model.TeacherCategoryModel>,
    val videoUrl: String?,
    val nearestSlotTime: String?,
    val currency: String?,
    var isMailActivated: Boolean = false,
    var isMobileActivated: Boolean = false,
    val education: com.moddakir.moddakir.network.model.Education?,
    val childAgePreferanceForEdit: String = "",
    val childPathId: String = "",
    val childEducationPlanId: String = "",
    val childLinesPerSession: Int = 0,

    var briefTrans: BriefTrans? = null

    ) : Parcelable
